## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
features = application_df.drop(columns=["EIN", "NAME"])

In [ ]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
features.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
values = features['APPLICATION_TYPE'].value_counts()
values

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
values[values < 500].index

Index(['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17'], dtype='object', name='APPLICATION_TYPE')

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = []
for val in (values[values < 500].index):
  application_types_to_replace.append(val)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
class_values = features['CLASSIFICATION'].value_counts()
class_values

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
class_values[class_values > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = []
for val in (class_values[class_values < 1800].index):
  classifications_to_replace.append(val)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
numeric_df = pd.get_dummies(features)
numeric_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [ ]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
X = numeric_df.drop(columns=["IS_SUCCESSFUL"])
y = numeric_df["IS_SUCCESSFUL"]

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
r_state = 42

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = r_state)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
len(X_train_scaled[0])

116

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 =  200 # First attempt: 8; Second: 42; Third: 100
hidden_nodes_layer2 = 100 # First attempt: 5; Second: 15; Third: 50
hidden_nodes_layer3 = 15  # Added on 4th try.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

In [ ]:
 # Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [166]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5274 - accuracy: 0.7422
Epoch 2/50
804/804 [==============================] - 6s 8ms/step - loss: 0.5282 - accuracy: 0.7413
Epoch 3/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5271 - accuracy: 0.7426
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5273 - accuracy: 0.7416
Epoch 5/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5275 - accuracy: 0.7417
Epoch 6/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5269 - accuracy: 0.7410
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5269 - accuracy: 0.7419
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5268 - accuracy: 0.7423
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5264 - accuracy: 0.7428
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5267 - accuracy: 0.7422
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5260 - accuracy: 0.7420
Epoch 12/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5259 - accuracy: 0.7427
Epoch 13/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5271 - accuracy: 0.7423
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5260 - accuracy: 0.7427
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5257 - accuracy: 0.7422
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5260 - accuracy: 0.7431
Epoch 17/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5256 - accuracy: 0.7437
Epoch 18/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5259 - accuracy: 0.7432
Epoch 19/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5256 - accuracy: 0.7425
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7430
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5252 - accuracy: 0.7434
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5254 - accuracy: 0.7432
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5252 - accuracy: 0.7427
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5259 - accuracy: 0.7423
Epoch 25/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5252 - accuracy: 0.7433
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5250 - accuracy: 0.7427
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5254 - accuracy: 0.7434
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7432
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5247 - accuracy: 0.7430
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7429
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7437
Epoch 32/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5250 - accuracy: 0.7439
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5252 - accuracy: 0.7430
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7437
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5248 - accuracy: 0.7444
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5251 - accuracy: 0.7428
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5245 - accuracy: 0.7438
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5242 - accuracy: 0.7431
Epoch 39/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5242 - accuracy: 0.7434
Epoch 40/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5252 - accuracy: 0.7432
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5246 - accuracy: 0.7435
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5239 - accuracy: 0.7438
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5241 - accuracy: 0.7445
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5240 - accuracy: 0.7437
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5239 - accuracy: 0.7438
Epoch 46/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5242 - accuracy: 0.7432
Epoch 47/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5241 - accuracy: 0.7434
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5244 - accuracy: 0.7437
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5241 - accuracy: 0.7442
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5249 - accuracy: 0.7434

In [168]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5759 - accuracy: 0.7292 - 349ms/epoch - 1ms/step
Loss: 0.5759134292602539, Accuracy: 0.7292128205299377

In [171]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
from google.colab import files
nn.save('AlphabetSoupCharity.h5')

files.download("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(